name: Build LaTeX document
on:
  push:
    branches: ["master"]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: thesis_document/current
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Proyecto Integrador - PDF
          path: thesis_document/current/main.pdf
